# Generated by Django 4.1.6 on 2023-04-09 09:50

import django.core.validators
from django.db import migrations, models
import users.validtors


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[users.validtors.check_birth_date]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Ргистрация с домена rambler.ru запрещена!', regex='@rambler.ru')]),
        ),
    ]
